from . import ed_student
from . import ed_group
from . import ed_attend
from . import ed_time
from . import ed_eval
from . import ed_eval_result
from . import ed_event
from . import ed_calendar
from . import ed_notice
from . import ed_fee
from . import ed_payment
from . import ed_meal
from . import ed_homework
from . import ed_course
from . import ed_period
from . import ed_meeting
from . import ed_teacher
from . import ed_media
