from . import lazada_account
from . import sync_record
from . import product
#from . import product_categ
#from . import product_brand
from . import ship_method
from . import sale_order
from . import contact
from . import product_lazada_details
from . import lazada_settings
from . import stock_picking
from . import lazada_order
from . import lazada_order_item
from . import lazada_webhook
from . import stock_move
from . import lazada_product
from . import lazada_product_categ
from . import lazada_product_variation
from . import lazada_product_variation_option
from . import lazada_product_model
from . import lazada_order_shipping
