from . import l2g_truck
from . import l2g_driver
from . import l2g_customer
from . import l2g_booking
from . import l2g_booking_line
from . import l2g_job
from . import l2g_truck_type
from . import l2g_api
from . import l2g_pricelist
from . import l2g_price
from . import l2g_province
from . import l2g_transporter
from . import l2g_weight_range
from . import l2g_trans
from . import l2g_loc_update
from . import l2g_location
from . import menu
from . import chat_channel
from . import chat_message
from . import l2g_min_weight
from . import l2g_penalty
from . import l2g_company
from . import l2g_product
from . import l2g_product_option
from . import l2g_booking_product
from . import l2g_get_addr
from . import l2g_driver_group
from . import l2g_product_type
from . import l2g_serv_req
